
name: Deploy to EC2 using Docker

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2 ##docker login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./ThinkSphere-frontend
          file: ./ThinkSphere-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/thinksphere-frontend:${{ github.sha }}


      - name: SSH and deploy to VM
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.EC2_HOST }} "
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/thinksphere-frontend:${{ github.sha }} &&
            sudo docker stop thinksphere-frontend || true &&
            sudo docker rm thinksphere-frontend || true &&
            sudo docker run -d --name thinksphere-frontend -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/thinksphere-frontend:${{ github.sha }}      